name: yesssirbox
version: master-2.5
main: xyz.skaerf.yesssirbox.Yesssirbox
api-version: 1.18
depend: [Vault]
commands:
  yesssirbox:
    usage: /yesssirbox <reload/addBlock> [value]
    aliases: [yb,ysb]
  discord:
    usage: /discord
