name: yesssirbox
version: master-2.5
authors: [skaerf, Sidiju]
main: xyz.skaerf.yesssirbox.Yesssirbox
api-version: 1.18
depend: [Vault]
commands:
  yesssirbox:
    usage: /yesssirbox <reload/addBlock> [value]
    aliases: [yb,ysb]
  discord:
    usage: /discord
  shop:
    usage: /shop
  bounty:
    usage: /bounty
  autocompressor:
    usage: /autocompressor
  autocompress:
    description: turns Autocompressor on
    aliases: [ ac,autocomp ]
  compress:
    description: Compresses CommandSender's Item
    aliases: compressor
  vote:
    description: puts Vote-Links into Player's Chat
  offhand:
    description: Switches the item in your main hand with your offhand
