name: YessirBox
version: '${version}'
main: me.trouper.yessirbox.YessirBox
api-version: 1.20
authors: [ ImproperIssues ]
description: im lazy
commands:
  compress:
    usage: /compress
    permission: yessirbox.compress
  ysb:
    usage: /ysb <compress> <add|remove>
    permission: yessirbox.admin
  autocompressor:
    usage: /autocompressor
    permission: yessirbox.autocompressor
  bounty:
    usage: /bounty <set|cancel|check> <player> [<amount>] [<duration>]
  discord:
    usage: /discord
  vote:
    usage: /vote
  showdonation:
    usage: /showdonation <player> <amount> <price> <product>
    permission: yessirbox.showdonation
  store:
    usage: /store
permissions:
  yessirbox.admin:
    description: Allows full access to the /ysb admin command
  yessirbox.compress:
    decription: Ability to use the /compress command
  yessirbox.toggleautocompress:
    description: Allows access to the autoCompression enchant, and toggle command
  yessirbox.showdonation:
    description: Allows showing donator heads in chat
